# Generated by Django 2.0.13 on 2020-07-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={},
        ),
        migrations.RemoveField(
            model_name='tree',
            name='path',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='public',
        ),
    ]
